name: Rem
description: "A reminder application which reminds you again and again until you finish the job."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.4
  archive: ^3.6.1
  awesome_notifications: ^0.10.0
  double_back_to_close_app: ^2.1.0
  duration: ^4.0.3
  dynamic_color: ^1.7.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  hive_ce: ^2.10.0
  hive_ce_flutter: ^2.2.0
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  logger: ^2.4.0
  mutex: ^3.1.0
  package_info_plus: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  random_datetime: ^1.0.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.1
  toastification: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  very_good_analysis: ^7.0.0

flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
