// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:Rem/core/models/no_rush_reminders/no_rush_reminders.dart';
import 'package:Rem/core/models/recurring_interval/recurring_interval.dart';
import 'package:Rem/core/models/recurring_reminder/recurring_reminder.dart';
import 'package:Rem/core/models/reminder_model/reminder_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoRushRemindersModelAdapter());
    registerAdapter(RecurringIntervalAdapter());
    registerAdapter(RecurringReminderModelAdapter());
    registerAdapter(ReminderModelAdapter());
  }
}
