import '../../feature/reminder/data/models/no_rush_reminder.dart';
import '../../feature/reminder/data/models/reminder_base.dart';

@pragma('vm:entry-point')
class IdHandler {
  /// Creates a new notification id using the passed [id].
  /// [id] is usually the reminder's id.
  ///
  /// Notification id is created by joining [id] and the seconds
  /// since epoch
  @pragma('vm:entry-point')
  static int getReminderNotificationId(int id) {
    final int secondsSinceEpoch =
        DateTime.now().millisecondsSinceEpoch ~/ Duration.millisecondsPerSecond;
    final String seconds = secondsSinceEpoch.toString();
    final int len = seconds.length;
    return int.parse(id.toString() + seconds.substring(len - 6));
  }

  /// Id for the Alarm Manager.
  /// Since [reminder].id is generated by objectbox and,
  /// normal and noRush reminders have different boxes, their ids
  /// may collide. So we add 100000 to no rush ids.
  @pragma('vm:entry-point')
  static int getReminderAlarmId(ReminderBase reminder) {
    if (reminder is NoRushReminderModel) {
      return reminder.id + 100000;
    } else {
      return reminder.id;
    }
  }

  /// Gets the string ground key for notifications of reminders.
  @pragma('vm:entry-point')
  static String getReminderGroupKey(ReminderBase reminder) {
    if (reminder is NoRushReminderModel) {
      return 'noRush${reminder.id}';
    }
    return reminder.id.toString();
  }

  /// Since there will always be a single alarm for agenda, constant id.
  @pragma('vm:entry-point')
  static int get agendaAlarmId => 99; // Temporary value

  /// Since agenda notification's are supposed to be overritten,
  /// constant id.
  @pragma('vm:entry-point')
  static int get agendaNotificationId => 100000000; // Temporary value
}
